project_id = "iqjpwazeytothqzmzfcu"

[functions.order-action]
verify_jwt = true

[functions.get-signed-upload-url]
verify_jwt = true

[functions.get-signed-download-url]
verify_jwt = true

[functions.convert-inquiry-to-order]
verify_jwt = false
