import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Sparkles, 
  FileText, 
  ArrowRight, 
  ArrowLeft,
  Download,
  Send,
  CheckCircle,
  Loader2,
  Pencil,
  Copy
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

interface RFQData {
  productType: string;
  description: string;
  materials: string;
  quantity: string;
  targetPrice: string;
  timeline: string;
  certifications: string[];
  additionalRequirements: string;
}

const steps = [
  { id: 1, label: "Product", description: "What are you making?" },
  { id: 2, label: "Specifications", description: "Materials & details" },
  { id: 3, label: "Requirements", description: "Quantity & timeline" },
  { id: 4, label: "Review", description: "Preview & generate" },
];

const certificationOptions = [
  "GOTS Organic",
  "OEKO-TEX",
  "Fair Trade",
  "BSCI",
  "ISO 9001",
  "GRS Recycled"
];

interface AIRFQGeneratorProps {
  className?: string;
}

export function AIRFQGenerator({ className }: AIRFQGeneratorProps) {
  const [currentStep, setCurrentStep] = useState(1);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedRFQ, setGeneratedRFQ] = useState<string | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  
  const [formData, setFormData] = useState<RFQData>({
    productType: "",
    description: "",
    materials: "",
    quantity: "",
    targetPrice: "",
    timeline: "",
    certifications: [],
    additionalRequirements: "",
  });

  const updateFormData = (field: keyof RFQData, value: string | string[]) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const toggleCertification = (cert: string) => {
    setFormData(prev => ({
      ...prev,
      certifications: prev.certifications.includes(cert)
        ? prev.certifications.filter(c => c !== cert)
        : [...prev.certifications, cert]
    }));
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setGeneratedRFQ(`
# Request for Quotation (RFQ)

## Product Overview
**Product Type:** ${formData.productType || "Sustainable Swimwear Collection"}
**Description:** ${formData.description || "Women's one-piece and two-piece swimwear in 4 colorways"}

## Technical Specifications
**Materials Required:**
${formData.materials || "- ECONYL® Regenerated Nylon (78%)\n- Elastane (22%)\n- UV-resistant finish\n- Chlorine-resistant treatment"}

**Construction Details:**
- Flatlock stitching throughout
- Internal shelf bra with removable padding
- Fully lined front panel
- Heat-transferred size labels

## Order Requirements
**Quantity:** ${formData.quantity || "500 units per style (2,000 total)"}
**Target Unit Price:** ${formData.targetPrice || "$12-15 USD FOB"}
**Required Delivery:** ${formData.timeline || "8-10 weeks from approval"}

## Certifications Required
${formData.certifications.length > 0 ? formData.certifications.map(c => `- ${c}`).join("\n") : "- OEKO-TEX Standard 100\n- GRS Certified materials preferred"}

## Additional Requirements
${formData.additionalRequirements || "- Size range: XS-XL (5 sizes)\n- Custom hangtags and poly bags\n- Pre-shipment quality inspection\n- Digital tech pack will be provided"}

## Contact Information
Please respond with:
1. Unit pricing breakdown by quantity tier
2. Estimated lead time
3. Sample cost and timeline
4. Payment terms
5. Recent references for similar products

---
*Generated by Sourcery AI • ${new Date().toLocaleDateString()}*
      `.trim());
      setIsGenerating(false);
      setCurrentStep(5);
    }, 2500);
  };

  const handleCopy = () => {
    if (generatedRFQ) {
      navigator.clipboard.writeText(generatedRFQ);
      toast.success("RFQ copied to clipboard!");
    }
  };

  const handleSendToFactories = () => {
    toast.success("RFQ will be sent to selected factories!");
  };

  return (
    <div className={cn("bg-card border border-border rounded-xl overflow-hidden", className)}>
      {/* Header */}
      <div className="bg-gradient-to-r from-primary/10 via-primary/5 to-transparent p-6 border-b border-border">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center">
            <FileText className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h3 className="font-heading font-semibold text-foreground">
              AI RFQ Generator
            </h3>
            <p className="text-sm text-muted-foreground">
              Create professional RFQs from simple descriptions
            </p>
          </div>
        </div>
      </div>

      {/* Progress Steps */}
      {currentStep <= 4 && (
        <div className="px-6 pt-6">
          <div className="flex items-center justify-between mb-6">
            {steps.map((step, index) => (
              <div key={step.id} className="flex items-center">
                <div className="flex flex-col items-center">
                  <div className={cn(
                    "w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors",
                    currentStep >= step.id 
                      ? "bg-primary text-primary-foreground" 
                      : "bg-muted text-muted-foreground"
                  )}>
                    {currentStep > step.id ? (
                      <CheckCircle className="w-4 h-4" />
                    ) : (
                      step.id
                    )}
                  </div>
                  <span className="text-xs text-muted-foreground mt-1 hidden sm:block">
                    {step.label}
                  </span>
                </div>
                {index < steps.length - 1 && (
                  <div className={cn(
                    "w-12 sm:w-20 h-0.5 mx-2",
                    currentStep > step.id ? "bg-primary" : "bg-muted"
                  )} />
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="p-6">
        <AnimatePresence mode="wait">
          {/* Step 1: Product Type */}
          {currentStep === 1 && (
            <motion.div
              key="step1"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-4"
            >
              <div>
                <label className="text-sm font-medium text-foreground block mb-2">
                  What type of product are you making?
                </label>
                <input
                  type="text"
                  value={formData.productType}
                  onChange={(e) => updateFormData("productType", e.target.value)}
                  placeholder="e.g., Sustainable swimwear collection"
                  className="w-full p-3 bg-muted rounded-lg border border-border focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all"
                />
              </div>
              <div>
                <label className="text-sm font-medium text-foreground block mb-2">
                  Describe your product in detail
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) => updateFormData("description", e.target.value)}
                  placeholder="e.g., Women's one-piece and two-piece swimwear in 4 colorways, targeting the sustainable luxury market..."
                  rows={4}
                  className="w-full p-3 bg-muted rounded-lg border border-border focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all resize-none"
                />
              </div>
            </motion.div>
          )}

          {/* Step 2: Specifications */}
          {currentStep === 2 && (
            <motion.div
              key="step2"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-4"
            >
              <div>
                <label className="text-sm font-medium text-foreground block mb-2">
                  What materials do you want to use?
                </label>
                <textarea
                  value={formData.materials}
                  onChange={(e) => updateFormData("materials", e.target.value)}
                  placeholder="e.g., Recycled nylon with elastane, UV-resistant finish..."
                  rows={3}
                  className="w-full p-3 bg-muted rounded-lg border border-border focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all resize-none"
                />
              </div>
              <div>
                <label className="text-sm font-medium text-foreground block mb-2">
                  Required certifications
                </label>
                <div className="flex flex-wrap gap-2">
                  {certificationOptions.map((cert) => (
                    <Badge
                      key={cert}
                      variant={formData.certifications.includes(cert) ? "default" : "outline"}
                      className="cursor-pointer"
                      onClick={() => toggleCertification(cert)}
                    >
                      {formData.certifications.includes(cert) && (
                        <CheckCircle className="w-3 h-3 mr-1" />
                      )}
                      {cert}
                    </Badge>
                  ))}
                </div>
              </div>
            </motion.div>
          )}

          {/* Step 3: Requirements */}
          {currentStep === 3 && (
            <motion.div
              key="step3"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-4"
            >
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-sm font-medium text-foreground block mb-2">
                    Order quantity
                  </label>
                  <input
                    type="text"
                    value={formData.quantity}
                    onChange={(e) => updateFormData("quantity", e.target.value)}
                    placeholder="e.g., 500 units per style"
                    className="w-full p-3 bg-muted rounded-lg border border-border focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium text-foreground block mb-2">
                    Target price range
                  </label>
                  <input
                    type="text"
                    value={formData.targetPrice}
                    onChange={(e) => updateFormData("targetPrice", e.target.value)}
                    placeholder="e.g., $12-15 USD/unit"
                    className="w-full p-3 bg-muted rounded-lg border border-border focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all"
                  />
                </div>
              </div>
              <div>
                <label className="text-sm font-medium text-foreground block mb-2">
                  Delivery timeline
                </label>
                <input
                  type="text"
                  value={formData.timeline}
                  onChange={(e) => updateFormData("timeline", e.target.value)}
                  placeholder="e.g., 8-10 weeks from approval"
                  className="w-full p-3 bg-muted rounded-lg border border-border focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all"
                />
              </div>
              <div>
                <label className="text-sm font-medium text-foreground block mb-2">
                  Additional requirements (optional)
                </label>
                <textarea
                  value={formData.additionalRequirements}
                  onChange={(e) => updateFormData("additionalRequirements", e.target.value)}
                  placeholder="e.g., Size range, packaging requirements, labeling..."
                  rows={3}
                  className="w-full p-3 bg-muted rounded-lg border border-border focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all resize-none"
                />
              </div>
            </motion.div>
          )}

          {/* Step 4: Review */}
          {currentStep === 4 && (
            <motion.div
              key="step4"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-4"
            >
              <div className="bg-muted/50 rounded-lg p-4 border border-border">
                <h4 className="font-medium text-foreground mb-3">Review Your Input</h4>
                <dl className="space-y-2 text-sm">
                  <div className="flex gap-2">
                    <dt className="text-muted-foreground w-28 shrink-0">Product:</dt>
                    <dd className="text-foreground">{formData.productType || "Not specified"}</dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="text-muted-foreground w-28 shrink-0">Quantity:</dt>
                    <dd className="text-foreground">{formData.quantity || "Not specified"}</dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="text-muted-foreground w-28 shrink-0">Target Price:</dt>
                    <dd className="text-foreground">{formData.targetPrice || "Not specified"}</dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="text-muted-foreground w-28 shrink-0">Timeline:</dt>
                    <dd className="text-foreground">{formData.timeline || "Not specified"}</dd>
                  </div>
                  {formData.certifications.length > 0 && (
                    <div className="flex gap-2">
                      <dt className="text-muted-foreground w-28 shrink-0">Certifications:</dt>
                      <dd className="text-foreground">{formData.certifications.join(", ")}</dd>
                    </div>
                  )}
                </dl>
              </div>

              <div className="text-center py-4">
                <Sparkles className="w-8 h-8 text-primary mx-auto mb-2" />
                <p className="text-sm text-muted-foreground">
                  AI will generate a professional RFQ document with industry-standard formatting
                </p>
              </div>
            </motion.div>
          )}

          {/* Generating State */}
          {isGenerating && (
            <motion.div
              key="generating"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="py-12 text-center"
            >
              <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-primary/10 flex items-center justify-center">
                <Sparkles className="w-8 h-8 text-primary animate-pulse" />
              </div>
              <h4 className="font-heading font-medium text-foreground mb-2">
                Generating your RFQ...
              </h4>
              <div className="space-y-2 text-sm text-muted-foreground">
                <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }}>
                  ✓ Analyzing product requirements
                </motion.p>
                <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.8 }}>
                  ✓ Adding industry-standard specifications
                </motion.p>
                <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.3 }}>
                  ✓ Formatting professional document
                </motion.p>
                <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.8 }} className="text-primary">
                  ✓ Finalizing RFQ...
                </motion.p>
              </div>
            </motion.div>
          )}

          {/* Generated RFQ */}
          {currentStep === 5 && generatedRFQ && !isGenerating && (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-4"
            >
              <div className="flex items-center justify-between">
                <Badge className="bg-emerald-500/10 text-emerald-600">
                  <CheckCircle className="w-3 h-3 mr-1" />
                  RFQ Generated
                </Badge>
                <div className="flex gap-2">
                  <Button variant="ghost" size="sm" onClick={() => setIsEditing(!isEditing)}>
                    <Pencil className="w-4 h-4 mr-1" />
                    {isEditing ? "Preview" : "Edit"}
                  </Button>
                  <Button variant="ghost" size="sm" onClick={handleCopy}>
                    <Copy className="w-4 h-4 mr-1" />
                    Copy
                  </Button>
                </div>
              </div>

              {isEditing ? (
                <textarea
                  value={generatedRFQ}
                  onChange={(e) => setGeneratedRFQ(e.target.value)}
                  className="w-full h-96 p-4 bg-muted rounded-lg border border-border font-mono text-sm resize-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                />
              ) : (
                <div className="bg-muted/50 rounded-lg p-4 border border-border max-h-96 overflow-y-auto">
                  <pre className="whitespace-pre-wrap text-sm text-foreground font-sans">
                    {generatedRFQ}
                  </pre>
                </div>
              )}

              <div className="flex gap-3">
                <Button variant="outline" className="flex-1">
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </Button>
                <Button className="flex-1" onClick={handleSendToFactories}>
                  <Send className="w-4 h-4 mr-2" />
                  Send to Factories
                </Button>
              </div>

              <Button 
                variant="ghost" 
                className="w-full"
                onClick={() => {
                  setCurrentStep(1);
                  setGeneratedRFQ(null);
                }}
              >
                <ArrowLeft className="w-4 h-4 mr-2" />
                Create Another RFQ
              </Button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Navigation */}
        {currentStep <= 4 && !isGenerating && (
          <div className="flex justify-between mt-6 pt-4 border-t border-border">
            <Button
              variant="ghost"
              onClick={() => setCurrentStep(Math.max(1, currentStep - 1))}
              disabled={currentStep === 1}
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
            
            {currentStep < 4 ? (
              <Button onClick={() => setCurrentStep(currentStep + 1)}>
                Continue
                <ArrowRight className="w-4 h-4 ml-2" />
              </Button>
            ) : (
              <Button onClick={handleGenerate}>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate RFQ
              </Button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
